package uz.notgis.documate

/** Interfeys matnlari: o'zbek / rus / ingliz. Hozircha barcha ekranlar shu orqali tarjima qilinadi. */
data class L(
    val home: String,
    val tools: String,
    val favs: String,
    val settings: String,
    val docs: String,
    val searchHint: String,
    val all: String,
    val filesCount: String,
    val sort: String,
    val notFound: String,
    val pickFolder: String,
    val pickFolderBody: String,
    val changeFolder: String,
    val folder: String,
    val notChosen: String,
    val theme: String,
    val system: String,
    val light: String,
    val dark: String,
    val privacy: String,
    val about: String,
    val language: String,
    val lock: String,
    val lockBody: String,
    val setPin: String,
    val enterPin: String,
    val pinWrong: String,
    val pinSaved: String,
    val unlockTitle: String,
    val unlockHint: String,
    val open: String,
    val openExternal: String,
    val back: String,
    val day: String,
    val night: String,
    val searchPdf: String,
    val foundOnPages: String,
    val passwordTitle: String,
    val passwordHint: String,
    val passwordWrong: String,
    val continueLast: String,
    val toolsImagePdf: String,
    val toolsImagePdfBody: String,
    val toolsCamera: String,
    val toolsCameraBody: String,
    val toolsMerge: String,
    val toolsMergeBody: String,
    val toolsText: String,
    val toolsTextBody: String,
    val toolsTemplates: String,
    val toolsTemplatesBody: String,
    val soon: String,
    val ocrNote: String,
    val start: String,
    val creating: String,
    val saved: String,
    val failed: String,
    val internalViewer: String,
    val oldFormatNote: String,
    val noApp: String,
)

val Uz = L(
    home = "Bosh sahifa", tools = "Asboblar", favs = "Sevimlilar", settings = "Sozlamalar",
    docs = "Hujjatlarim", searchHint = "Fayl nomi bo'yicha qidirish", all = "Hammasi",
    filesCount = "ta fayl", sort = "Saralash", notFound = "Hech narsa topilmadi",
    pickFolder = "Papkani tanlash", pickFolderBody = "DocuMate «barcha fayllarni boshqarish» ruxsatini so'ramaydi. Hujjatlaringiz turgan papkani o'zingiz ko'rsatasiz — ilova faqat shu papkani o'qiydi.",
    changeFolder = "Papkani o'zgartirish", folder = "Hujjatlar papkasi", notChosen = "Tanlanmagan",
    theme = "Mavzu", system = "Tizim", light = "Yorug'", dark = "Qorong'i",
    privacy = "Maxfiylik", about = "Ilova haqida", language = "Til",
    lock = "Qulf (PIN)", lockBody = "Ilova ochilganda 4 xonali PIN so'raladi. Hammasi qurilmada saqlanadi.",
    setPin = "PIN o'rnatish", enterPin = "Yangi 4 xonali PIN", pinWrong = "PIN noto'g'ri. Qayta urining.",
    pinSaved = "PIN saqlandi.", unlockTitle = "DocuMate qulflangan", unlockHint = "Davom etish uchun PIN ni kiriting",
    open = "Ochish", openExternal = "Boshqa ilovada ochish", back = "Orqaga",
    day = "Kun", night = "Tun", searchPdf = "Matn qidirish…",
    foundOnPages = "topildi", passwordTitle = "Parolli PDF", passwordHint = "PDF parolini kiriting",
    passwordWrong = "Parol noto'g'ri yoki fayl ochilmadi.",
    continueLast = "Qolgan joydan davom etish",
    toolsImagePdf = "Rasm → PDF", toolsImagePdfBody = "Galereyadan bir nechta rasmni tanlang — har biri A4 sahifa bo'ladi.",
    toolsCamera = "Kamera bilan skanerlash", toolsCameraBody = "Hujjatni suratga oling — avtomatik PDF ga qo'shiladi. OCR (matn ajratish) keyingi bosqichda, offline model bilan keladi.",
    toolsMerge = "PDF birlashtirish", toolsMergeBody = "2 yoki undan ko'p PDF ni bitta faylga qo'shadi (qurilmada).",
    toolsText = "Matn → PDF", toolsTextBody = "TXT/MD faylni PDF ga aylantiradi.",
    toolsTemplates = "Shablonlar", toolsTemplatesBody = "Ariza va rezyume shablonidan PDF yaratadi.",
    soon = "Tez orada", ocrNote = "Skaner ishlaydi (kamera → PDF). OCR matn ajratish «Tez orada».",
    start = "Boshlash", creating = "Yaratilmoqda…", saved = "saqlandi", failed = "bo'lmadi",
    internalViewer = "Ichki ko'ruvchi", oldFormatNote = "Eski format (.doc/.xls/.ppt): ichki matn ko'rinishi cheklangan, «Boshqa ilovada ochish» dan foydalaning.",
    noApp = "Mos ilova topilmadi.",
)

val Ru = L(
    home = "Главная", tools = "Инструменты", favs = "Избранное", settings = "Настройки",
    docs = "Мои документы", searchHint = "Поиск по имени файла", all = "Все",
    filesCount = "файлов", sort = "Сортировка", notFound = "Ничего не найдено",
    pickFolder = "Выбрать папку", pickFolderBody = "DocuMate не просит доступ ко всем файлам. Выберите папку с документами — приложение читает только её.",
    changeFolder = "Изменить папку", folder = "Папка документов", notChosen = "Не выбрана",
    theme = "Тема", system = "Система", light = "Светлая", dark = "Тёмная",
    privacy = "Конфиденциальность", about = "О приложении", language = "Язык",
    lock = "Блокировка (PIN)", lockBody = "При открытии приложения запрашивается 4-значный PIN. Всё хранится на устройстве.",
    setPin = "Установить PIN", enterPin = "Новый 4-значный PIN", pinWrong = "Неверный PIN. Попробуйте снова.",
    pinSaved = "PIN сохранён.", unlockTitle = "DocuMate заблокирован", unlockHint = "Введите PIN чтобы продолжить",
    open = "Открыть", openExternal = "Открыть в другом приложении", back = "Назад",
    day = "День", night = "Ночь", searchPdf = "Поиск по тексту…",
    foundOnPages = "найдено", passwordTitle = "PDF с паролем", passwordHint = "Введите пароль PDF",
    passwordWrong = "Неверный пароль или файл не открылся.",
    continueLast = "Продолжить с места остановки",
    toolsImagePdf = "Фото → PDF", toolsImagePdfBody = "Выберите несколько фото — каждое станет страницей A4.",
    toolsCamera = "Сканирование камерой", toolsCameraBody = "Сфотографируйте документ — он добавится в PDF. OCR будет в следующем этапе (офлайн-модель).",
    toolsMerge = "Объединить PDF", toolsMergeBody = "Склеивает 2+ PDF в один файл (на устройстве).",
    toolsText = "Текст → PDF", toolsTextBody = "Конвертирует TXT/MD в PDF.",
    toolsTemplates = "Шаблоны", toolsTemplatesBody = "Создаёт PDF из шаблонов заявления и резюме.",
    soon = "Скоро", ocrNote = "Сканер работает (камера → PDF). Распознавание текста (OCR) — «Скоро».",
    start = "Начать", creating = "Создание…", saved = "сохранено", failed = "не получилось",
    internalViewer = "Встроенный просмотр", oldFormatNote = "Старый формат (.doc/.xls/.ppt): встроенный показ ограничен, используйте «Открыть в другом приложении».",
    noApp = "Подходящее приложение не найдено.",
)

val En = L(
    home = "Home", tools = "Tools", favs = "Favorites", settings = "Settings",
    docs = "My documents", searchHint = "Search by file name", all = "All",
    filesCount = "files", sort = "Sort", notFound = "Nothing found",
    pickFolder = "Choose folder", pickFolderBody = "DocuMate never asks for all-files access. Pick the folder with your documents — the app reads only that folder.",
    changeFolder = "Change folder", folder = "Documents folder", notChosen = "Not chosen",
    theme = "Theme", system = "System", light = "Light", dark = "Dark",
    privacy = "Privacy", about = "About", language = "Language",
    lock = "Lock (PIN)", lockBody = "Asks a 4-digit PIN when the app opens. Everything stays on-device.",
    setPin = "Set PIN", enterPin = "New 4-digit PIN", pinWrong = "Wrong PIN. Try again.",
    pinSaved = "PIN saved.", unlockTitle = "DocuMate is locked", unlockHint = "Enter PIN to continue",
    open = "Open", openExternal = "Open in another app", back = "Back",
    day = "Day", night = "Night", searchPdf = "Search text…",
    foundOnPages = "found", passwordTitle = "Password PDF", passwordHint = "Enter PDF password",
    passwordWrong = "Wrong password or file could not be opened.",
    continueLast = "Resume where you left",
    toolsImagePdf = "Images → PDF", toolsImagePdfBody = "Pick several images — each becomes an A4 page.",
    toolsCamera = "Scan with camera", toolsCameraBody = "Photograph a document — it is added to a PDF. OCR text recognition comes next (offline model).",
    toolsMerge = "Merge PDFs", toolsMergeBody = "Joins 2+ PDFs into one file (on-device).",
    toolsText = "Text → PDF", toolsTextBody = "Converts TXT/MD into PDF.",
    toolsTemplates = "Templates", toolsTemplatesBody = "Creates PDFs from application and CV templates.",
    soon = "Soon", ocrNote = "Scanner works (camera → PDF). OCR text extraction is marked “Soon”.",
    start = "Start", creating = "Creating…", saved = "saved", failed = "failed",
    internalViewer = "Built-in viewer", oldFormatNote = "Legacy format (.doc/.xls/.ppt): built-in preview is limited, use “Open in another app”.",
    noApp = "No suitable app found.",
)

fun stringsFor(lang: String): L = when (lang) {
    "ru" -> Ru
    "en" -> En
    else -> Uz
}
