package uz.notgis.documate

/** Interfeys matnlari: o'zbek / rus / ingliz. */
data class L(
    val home: String,
    val tools: String,
    val favs: String,
    val settings: String,
    val navHome: String,
    val navTools: String,
    val navFavs: String,
    val navSettings: String,
    val docs: String,
    val searchHint: String,
    val all: String,
    val filesCount: String,
    val sort: String,
    val notFound: String,
    val pickFolder: String,
    val pickFolderBody: String,
    val changeFolder: String,
    val folder: String,
    val notChosen: String,
    val allFiles: String,
    val permTitle: String,
    val permBody: String,
    val allowAll: String,
    val theme: String,
    val system: String,
    val light: String,
    val dark: String,
    val privacy: String,
    val about: String,
    val version: String,
    val language: String,
    val open: String,
    val openExternal: String,
    val back: String,
    val day: String,
    val night: String,
    val searchPdf: String,
    val foundOnPages: String,
    val passwordTitle: String,
    val passwordHint: String,
    val passwordWrong: String,
    val continueLast: String,
    val toolsImagePdf: String,
    val toolsImagePdfBody: String,
    val toolsCamera: String,
    val toolsCameraBody: String,
    val toolsMerge: String,
    val toolsMergeBody: String,
    val toolsText: String,
    val toolsTextBody: String,
    val toolsTemplates: String,
    val toolsTemplatesBody: String,
    val soon: String,
    val ocrNote: String,
    val start: String,
    val creating: String,
    val saved: String,
    val failed: String,
    val internalViewer: String,
    val oldFormatNote: String,
    val noApp: String,
    val cvName: String,
    val cvPhone: String,
    val cvExp: String,
)

val Uz = L(
    home = "Bosh sahifa", tools = "Asboblar", favs = "Sevimlilar", settings = "Sozlamalar",
    navHome = "Bosh", navTools = "Asboblar", navFavs = "Sevimli", navSettings = "Sozlama",
    docs = "Hujjatlarim", searchHint = "Fayl nomi bo'yicha qidirish", all = "Hammasi",
    filesCount = "ta fayl", sort = "Saralash", notFound = "Hech narsa topilmadi",
    pickFolder = "Papkani tanlash",
    pickFolderBody = "Quyidagi tugma orqali barcha fayllarga ruxsat bering — ilova telefondagi barcha hujjatlarni ko'rsatadi. Yoki faqat bitta papkani tanlashingiz ham mumkin.",
    changeFolder = "Papkani o'zgartirish", folder = "Hujjatlar manbai", notChosen = "Tanlanmagan",
    allFiles = "Hamma fayllar",
    permTitle = "Fayllarga ruxsat",
    permBody = "Barcha hujjatlarni ko'rish uchun ruxsat kerak.",
    allowAll = "Ruxsat berish",
    theme = "Mavzu", system = "Tizim", light = "Yorug'", dark = "Qorong'i",
    privacy = "Maxfiylik", about = "Ilova haqida", version = "Versiya", language = "Til",
    open = "Ochish", openExternal = "Boshqa ilovada ochish", back = "Orqaga",
    day = "Kun", night = "Tun", searchPdf = "Matn qidirish…",
    foundOnPages = "topildi", passwordTitle = "Parolli PDF", passwordHint = "PDF parolini kiriting",
    passwordWrong = "Parol noto'g'ri yoki fayl ochilmadi.",
    continueLast = "Qolgan joydan davom etish",
    toolsImagePdf = "Rasm → PDF", toolsImagePdfBody = "Galereyadan rasmlarni tanlang — har bir rasm o'z o'lchamiga mos sahifa bo'ladi.",
    toolsCamera = "Kamera bilan skanerlash", toolsCameraBody = "Hujjatni suratga oling — avtomatik PDF ga qo'shiladi. OCR (matn ajratish) keyingi bosqichda.",
    toolsMerge = "PDF birlashtirish", toolsMergeBody = "2 yoki undan ko'p PDF ni bitta faylga qo'shadi (qurilmada).",
    toolsText = "Matn → PDF", toolsTextBody = "TXT/MD faylni PDF ga aylantiradi.",
    toolsTemplates = "Rezyume shabloni", toolsTemplatesBody = "Ma'lumotlaringizni kiriting — tayyor rezyume PDF yaratiladi.",
    soon = "Tez orada", ocrNote = "Skaner ishlaydi (kamera → PDF). OCR matn ajratish «Tez orada».",
    start = "Boshlash", creating = "Yaratilmoqda…", saved = "saqlandi", failed = "bo'lmadi",
    internalViewer = "Ichki ko'ruvchi", oldFormatNote = "Eski format (.doc/.xls/.ppt): ichki matn ko'rinishi cheklangan, «Boshqa ilovada ochish» dan foydalaning.",
    noApp = "Mos ilova topilmadi.",
    cvName = "F.I.Sh", cvPhone = "Telefon", cvExp = "Tajriba va ko'nikmalar",
)

val Ru = L(
    home = "Главная", tools = "Инструменты", favs = "Избранное", settings = "Настройки",
    navHome = "Главная", navTools = "Сервис", navFavs = "Избран.", navSettings = "Настройки",
    docs = "Мои документы", searchHint = "Поиск по имени файла", all = "Все",
    filesCount = "файлов", sort = "Сортировка", notFound = "Ничего не найдено",
    pickFolder = "Выбрать папку",
    pickFolderBody = "Разрешите доступ ко всем файлам — приложение покажет все документы на телефоне. Или выберите только одну папку.",
    changeFolder = "Изменить папку", folder = "Источник документов", notChosen = "Не выбрана",
    allFiles = "Все файлы",
    permTitle = "Доступ к файлам",
    permBody = "Нужно разрешение, чтобы показать все документы.",
    allowAll = "Разрешить",
    theme = "Тема", system = "Система", light = "Светлая", dark = "Тёмная",
    privacy = "Конфиденциальность", about = "О приложении", version = "Версия", language = "Язык",
    open = "Открыть", openExternal = "Открыть в другом приложении", back = "Назад",
    day = "День", night = "Ночь", searchPdf = "Поиск по тексту…",
    foundOnPages = "найдено", passwordTitle = "PDF с паролем", passwordHint = "Введите пароль PDF",
    passwordWrong = "Неверный пароль или файл не открылся.",
    continueLast = "Продолжить с места остановки",
    toolsImagePdf = "Фото → PDF", toolsImagePdfBody = "Выберите фото — каждое станет страницей по размеру фото.",
    toolsCamera = "Сканирование камерой", toolsCameraBody = "Сфотографируйте документ — он добавится в PDF. OCR будет в следующем этапе.",
    toolsMerge = "Объединить PDF", toolsMergeBody = "Склеивает 2+ PDF в один файл (на устройстве).",
    toolsText = "Текст → PDF", toolsTextBody = "Конвертирует TXT/MD в PDF.",
    toolsTemplates = "Шаблон резюме", toolsTemplatesBody = "Введите данные — создастся готовое резюме в PDF.",
    soon = "Скоро", ocrNote = "Сканер работает (камера → PDF). Распознавание текста (OCR) — «Скоро».",
    start = "Начать", creating = "Создание…", saved = "сохранено", failed = "не получилось",
    internalViewer = "Встроенный просмотр", oldFormatNote = "Старый формат (.doc/.xls/.ppt): встроенный показ ограничен, используйте «Открыть в другом приложении».",
    noApp = "Подходящее приложение не найдено.",
    cvName = "Ф.И.О.", cvPhone = "Телефон", cvExp = "Опыт и навыки",
)

val En = L(
    home = "Home", tools = "Tools", favs = "Favorites", settings = "Settings",
    navHome = "Home", navTools = "Tools", navFavs = "Saved", navSettings = "Settings",
    docs = "My documents", searchHint = "Search by file name", all = "All",
    filesCount = "files", sort = "Sort", notFound = "Nothing found",
    pickFolder = "Choose folder",
    pickFolderBody = "Grant all-files access — the app will show every document on the phone. Or pick a single folder instead.",
    changeFolder = "Change folder", folder = "Documents source", notChosen = "Not chosen",
    allFiles = "All files",
    permTitle = "File access",
    permBody = "Permission is needed to show all documents.",
    allowAll = "Grant access",
    theme = "Theme", system = "System", light = "Light", dark = "Dark",
    privacy = "Privacy", about = "About", version = "Version", language = "Language",
    open = "Open", openExternal = "Open in another app", back = "Back",
    day = "Day", night = "Night", searchPdf = "Search text…",
    foundOnPages = "found", passwordTitle = "Password PDF", passwordHint = "Enter PDF password",
    passwordWrong = "Wrong password or file could not be opened.",
    continueLast = "Resume where you left",
    toolsImagePdf = "Images → PDF", toolsImagePdfBody = "Pick images — each becomes a page sized to the photo.",
    toolsCamera = "Scan with camera", toolsCameraBody = "Photograph a document — it is added to a PDF. OCR comes next.",
    toolsMerge = "Merge PDFs", toolsMergeBody = "Joins 2+ PDFs into one file (on-device).",
    toolsText = "Text → PDF", toolsTextBody = "Converts TXT/MD into PDF.",
    toolsTemplates = "CV template", toolsTemplatesBody = "Enter your details — a ready CV PDF is created.",
    soon = "Soon", ocrNote = "Scanner works (camera → PDF). OCR text extraction is marked “Soon”.",
    start = "Start", creating = "Creating…", saved = "saved", failed = "failed",
    internalViewer = "Built-in viewer", oldFormatNote = "Legacy format (.doc/.xls/.ppt): built-in preview is limited, use “Open in another app”.",
    noApp = "No suitable app found.",
    cvName = "Full name", cvPhone = "Phone", cvExp = "Experience & skills",
)

fun stringsFor(lang: String): L = when (lang) {
    "ru" -> Ru
    "en" -> En
    else -> Uz
}
